<?php

namespace App\Models;

use App\Constants\App;
use App\Constants\Commons\CommonStatusConst;
use Illuminate\Support\Facades\DB;

class BaseMasterModel extends BaseModel
{
    const PREFIX_CODE = null;

    public const TABLE_NAME = null;

    const MAX_LENGTH_CODE = 10;

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($model) {
            $currentNextId = with(new static);

            if ($model::PREFIX_CODE !== null && empty($model->code)) {
                $model->code = $model::PREFIX_CODE.str_pad($currentNextId->getNextID(), $model::getCountNumberCode(), '0', STR_PAD_LEFT);
            }

            if (isset(auth()->user()->code)) {
                $model->created_by = auth()->user()->code;
            }
        });

        static::updating(function ($model) {
            if (isset(auth()->user()->code)) {
                $model->updated_by = auth()->user()->code;
            }
        });
    }

    public function getNextID()
    {
        $tableName = static::getTableName();
        
        $maxId = DB::table($tableName)->max('id') ?? 0;

        // SQLite support for testing
        if (DB::getDriverName() === 'sqlite') {
            return $maxId + 1;
        }

        if (config('app.restart_cache_mysql') && DB::getDriverName() === 'mysql') {
            try {
                DB::statement('SET PERSIST information_schema_stats_expiry = 0');
            } catch (\Throwable $e) {}
        }

        $statement = DB::select("show table status like '{$tableName}'");
        $autoIncrement = $statement[0]->Auto_increment ?? 1;

        return max($autoIncrement, $maxId + 1);
    }

    protected static function getCountNumberCode()
    {
        return static::MAX_LENGTH_CODE - strlen(static::PREFIX_CODE);
    }

    public function scopeActive($query)
    {
        return $query->whereNotIn(App::STATUS, [CommonStatusConst::DELETED, CommonStatusConst::INACTIVE]);
    }

    public function scopeAvailable($query)
    {
        return $query->whereNot(App::STATUS, [CommonStatusConst::DELETED]);
    }
}
